### PR TITLE
I changed it to /usr/local/lsws/conf/httpd.conf > /usr/local/lsws/con…

### PR DESCRIPTION
**Pull request by erselbey**
…f/httpd_config.conf.

### CODE REVIEW

**Comment by istiak101** [comment]
This is not OLS config file.

**Comment by qtwrk** [comment]
> This is not OLS config file.

but still , I highly suggest NOT to use this file name , as it is default taken by OpenLiteSpeed for its main conf 

I wouldn't surprise if some tool or script do things like `[[ -f /usr/local/lsws/conf/httpd_config.conf ]]` to check the existence of OLS and that could mess something up.

better to use a file name that has not been used before anywhere by anything , maybe try thing like `cyberpanel-main.conf` or something...

**Comment by istiak101** [comment]
> > This is not OLS config file.
> 
> but still , I highly suggest NOT to use this file name , as it is default taken by OpenLiteSpeed for its main conf
> 
> I wouldn't surprise if some tool or script do things like `[[ -f /usr/local/lsws/conf/httpd_config.conf ]]` to check the existence of OLS and that could mess something up.
> 
> better to use a file name that has not been used before anywhere by anything , maybe try thing like `cyberpanel-main.conf` or something...

I agree. This is achievable as described in here https://openlitespeed.org/kb/directadmin-configuration-files/ . What I meant was OP modified the part that was supposed for LSWS Enterprise version.

**Comment by qtwrk** [comment]
> > > This is not OLS config file.
> > 
> > 
> > but still , I highly suggest NOT to use this file name , as it is default taken by OpenLiteSpeed for its main conf
> > I wouldn't surprise if some tool or script do things like `[[ -f /usr/local/lsws/conf/httpd_config.conf ]]` to check the existence of OLS and that could mess something up.
> > better to use a file name that has not been used before anywhere by anything , maybe try thing like `cyberpanel-main.conf` or something...
> 
> I agree. This is achievable as described in here https://openlitespeed.org/kb/directadmin-configuration-files/ . You can include your custom config file in the main config file. What I meant was OP modified the part that was supposed for LSWS Enterprise version.

no ,  I mean ,  some script or tool , could do check on file `/usr/local/lsws/conf/httpd_config.conf` to determinate if the server has OLS installed or not ,  with this file being used by something else, it could create trouble as it might mistakenly determinate the server is OLS while it actually doesn't

**Comment by usmannasir** [comment]
Will not merge this request.

**Pull request closed without merging**
