### PR TITLE
Update modSec.py

### PR DESCRIPTION
**Pull request by terlancenablari**
The latest version is 3.2

### CODE REVIEW

**Comment by usmannasir** [comment]
Is it compatible with ols/lsws ent?

**Comment by terlancenablari** [comment]
I think we should consider changing the URL related to this:

screenshot_28

The latest version is updated 11 days ago: https://github.com/coreruleset/coreruleset/archive/v3.3.2/master.zip

**Comment by terlancenablari** [comment]
I think we should consider changing the URL related to this: What do you think?

screenshot_28

**Comment by usmannasir** [comment]
But Is it compatible with ols/lsws ent?

**Comment by terlancenablari** [comment]
Yes. OLS/LSWS Ent using ModSecurity engine and is compatible with OWASP ModSecurity Core Rule Set.

**Comment by terlancenablari** [comment]
Yes. OLS and Lsws ent using ModSecurity engine and are compatible with OWASP ModSecurity Core Rule Set.

**Comment by terlancenablari** [comment]
but they moved to https://github.com/coreruleset/coreruleset/. that's why we should consider using this URL (https://github.com/coreruleset/coreruleset/archive/v3.3.2/master.zip)

**Pull request merged**
