### PR TITLE
Added favicon.png to admin dashboard

### PR DESCRIPTION
**Pull request by jordanlambrecht**
Added the CyberPanel favicon to the admin dashboard (please check my work and make sure I put favicon.png in the right static file location)

### CODE REVIEW

**Comment by meramsey** [comment]
nice work man this will definitely make all the cyberpanel tabs i have open less hard to find :)

**Comment by Bl0ck154** [comment]
I'm sorry, how to work this? I have latest version of Cyberpanel but it doesn't have Favicon

**Comment by inspiredearth** [comment]
> Added the CyberPanel favicon to the admin dashboard (please check my work and make sure I put favicon.png in the right static file location)

Would you please elaborate on where this was added in “the admin dashboard” ?

Thank you. 

**UPDATE**: I am now suspecting what @jordanlambrecht meant in his above text, is that he’s added a favicon to Cyberpanel (I assume it previously didn’t have one?), and was not referring to adding a configuration setting for specifying a custom favicon.

**Comment by jordanlambrecht** [comment]
@inspiredearth Correct

**Pull request merged**
