### PR TITLE
Fix https://github.com/usmannasir/cyberpanel/issues/842

### PR DESCRIPTION
**Pull request by Lvl4Sword**
As said in https://github.com/usmannasir/cyberpanel/issues/842#issuecomment-1816840750 , there's no reason not to have this as a list.

### CODE REVIEW

**Comment by Lvl4Sword** [comment]
Noticed the ip file is read within `listWebsitesJson`, but is never closed.
`with open()` ensures the file is closed without needing to explicitly call .close()

**Comment by Lvl4Sword** [comment]
I'm unsure as to why `checker` is here, ~~let alone why the ip file is even being read, since neither seem to really be used for anything.~~ since it doesn't seem to be used. The ip **is** used, because that needs provided to the user.. lol

**Comment by xmok** [comment]
Though not directly related to your PR, Issue #1145 I've opened deals with fixing JSON in the cloudApi which **does** relate to your previously opened Issue #842. Would be nice to get some feedback from the team on this as I've observed fixing the JSON handling also fixed some other minor errors thrown in the dashboard.

**Comment by usmannasir** [comment]
I had to change the base for this merge, thanks.

**Comment by Lvl4Sword** [comment]
Would you also accept cleaning up the rest of the CLI file to catch issues like this? I'd make separate issues if needed as well.

**Comment by usmannasir** [comment]
You have any pending PR?

If now I've no problem reviewing new and merging.

thank you.

> Would you also accept cleaning up the rest of the CLI file to catch issues like this? I'd make separate issues if needed as well.

**Comment by Lvl4Sword** [comment]
Not currently, but it'll be worked on this week. Glad to help! 👍

> You have any pending PR?
> 
> If now I've no problem reviewing new and merging.
> 
> thank you.
> 
> > Would you also accept cleaning up the rest of the CLI file to catch issues like this? I'd make separate issues if needed as well.

**Comment by usmannasir** [comment]
Here to help.

**Pull request merged**
