### PR TITLE
Update filemanager.py to fix filesize issues

### PR DESCRIPTION
**Pull request by meramsey**
Fix filesize issues https://github.com/usmannasir/cyberpanel/issues/146

### CODE REVIEW

**Comment by meramsey** [comment]
@usmannasir What do you think about merging this into dev and possible stable once tested?

**Comment by meramsey** [comment]
Example of it working 
Screenshot from 2023-11-23 12-44-51

**Comment by usmannasir** [comment]
Great, did you already test the working on your end ?

**Comment by usmannasir** [comment]
I've merged it, will test on my end too.

**Pull request merged**
