### PR TITLE
Replace Rainloop with SnappyMail

### PR DESCRIPTION
**Pull request by master3395**
This change is a draft. (Just duplicated from V2.3.1) so it should not have any old unchanged files.
I do not have the unzip method for tar.gz running where it was unzipping regular .zip

This change also includes the latest PHPMyAdmin 5.1.3

### CODE REVIEW

**Comment by master3395** [comment]
The difference between the download files are as following:

https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip

https://snappymail.eu/repository/latest.tar.gz

**Comment by usmannasir** [comment]
I will check this, can you mention line numbers where you need my attention.

**Comment by master3395** [comment]
> I will check this, can you mention line numbers where you need my attention.

plogical/upgrade.py - Line 407 command = 'wget https://snappymail.eu/repository/latest.tar.gz'

plogical/upgrade.py - Line 422 command = 'unzip latest.tar.gz -d /usr/local/CyberCP/public/snappymail'


install/venvsetup.sh - Line 89 sed -i 's|https://snappymail.eu/repository/latest.tar.gz|https://'$DOWNLOAD_SERVER'/repository/latest.tar.gz|g' install.py
install/install.py - Line 1244 command = 'wget https://snappymail.eu/repository/latest.tar.gz'

**Comment by usmannasir** [comment]
I've did some work on it today, but on default installation there is single folder only.

**Pull request merged**
