### PR TITLE
Add counter for # of commits since last update

### PR DESCRIPTION
**Pull request by nickchomey**
Adds a counter in Version Management to show how many commits have been made since the last update/current version.

### CODE REVIEW

**Comment by nickchomey** [comment]
image

**Comment by nickchomey** [comment]
Many people wont check the Version management tab very often, so it would be great if this check could run frequently/on every page load and a notice icon could be put either in the site header or in the Version Managment sidebar tab.

**Comment by nickchomey** [comment]
Dammit. I've messed something up with branches and bases. 

The only files that should be changing here are versionManagement.html and views.py

If you prefer, I can create a new PR. Just let me know which branch I should be trying to merge to. v.2.3.1-dev?

**Comment by master3395** [comment]
> Dammit. I've messed something up with branches and bases.
> 
> The only files that should be changing here are versionManagement.html and views.py
> 
> If you prefer, I can create a new PR. Just let me know which branch I should be trying to merge to. v.2.3.1-dev?

2.3.1-dev is non exsisting.
@usmannasir copied 2.1.3-dev into release (2.3.1 stable)

**Comment by usmannasir** [comment]
@master3395 @nickchomey I've merged this into `v2.1.3-dev` and then into our actual `v2.3.1` after checking the code, its good to go.

**Pull request merged**
