### PR TITLE
Master

### PR DESCRIPTION
**Pull request by meramsey**

### CODE REVIEW

**Comment by usmannasir** [comment]
It's a long pull request, you will have to discuss the changes with me on slack before I merge.

**Comment by meramsey** [comment]
hey I'm still learning git and I think it submitted it weird from the master vs the 1.8.0 as it had me merge vs how I was trying to do it one time for only the git commits

Id be happy to hop on discord\slack to chat so you can advise how is best to do this in least confusing way

I apologize for any confusion but essentially i was trying to standardize the dates and fix a typo in a bunch of the files.

let me know where i should chat with you.

**Comment by usmannasir** [comment]
What is your email, I will send you slack invite.

**Comment by meramsey** [comment]
sent you an email(the email on your github profile) with my email as I do not want it posted publicly here.

**Comment by usmannasir** [comment]
sent

**Pull request closed without merging**
