### PR TITLE
Issue SSL for SSL-enabled AliasDomains

### PR DESCRIPTION
**Pull request by speedpro**
Hi there,

I had an issue where I had a number of SSL enabled alias domains setup and I wanted them all to use the same base domain files. (e.g _base.com, alias1.com, alias2.com, alias3.com_.)

When I set up an alias domain (_alias1.com_), and hit 'Issue SSL', it would setup a cert that was issued to _base.com_, and _alias1.com_. Good.

But when I tried to setup _alias2.com_, and hit IssueSSL, it would overwrite the existing **alias1/base**  certificate with an **alias2/base** cert - meaning that _alias1.com_ was now throwing **invalid certificate** errors. 

I've rewritten the function that issues SSL for virtualhosts to issue a cert for all the SSL-enabled AliasDomains listed in the httpd-config listener section.

Let me know if I need to make any changes or improvements.

### CODE REVIEW

**Comment by usmannasir** [comment]
Will it fail if out of all domains one does not point to the server? (DNS Wise?)

**Comment by speedpro** [comment]
Yes, That seems to be the way that the letsencrypt system works, but the error message does display the problem domain/s.

If that was an issue for a sysadmin, then they could disable SSL for the problem domain until the DNS was setup.

**Comment by mario** [comment]
How come this wasn't merged yet?

**Comment by mario** [comment]
Anyone? :D

**Comment by istiak101** [comment]
@mario This pull request failed checks and at current time this might be very outdated to be merged. I think this can be closed.
@usmannasir

**Comment by mario** [comment]
Well I'd rather take a look at it and fix it because currently issuing SSL for domains which have alias domains fails :-/

**Comment by istiak101** [comment]
@mario if you can fix it create a pull request. Hopefully it will get merged.

**Pull request closed without merging**
