### PR TITLE
Fix #154

### LINKED ISSUE #154: DNS: Add/Delete domain alias and other extra dns
I dont know if a bug or an logical error. I can only manage records for websites.

In dnsManager.py
deleteDNSZone have
domainsList = ACLManager.findAllDomains(currentACL, userID)
addDeleteDNSRecords have
domainsList = ACLManager.findAllWebsites(currentACL, userID)

I believe domainsList in addDelete have to be the same than in delete, and this is a bug

### PR DESCRIPTION
**Pull request by ecreality**
https://github.com/usmannasir/cyberpanel/issues/154#issue-514132759

### CODE REVIEW

**Comment by usmannasir** [comment]
Some more details, please?

**Comment by ecreality** [comment]
As I can saw in Bug #154 , I believe DNS Manager is "independent" of "website management", but when I go to "Add/Modify DNS Zone", I only can see "website domains" (not all dns domains), in front of "Delete DNS Zone" that show all domains (what I think is the right option).
I change in those commits two lines to "fix" this "bug", and allow DNS Manager Add/Modify DNS Zones that doesn't have website associated.

**Comment by thomassiskos** [comment]
Greek Translate 1.9.2 Full
[gr.zip](https://github.com/usmannasir/cyberpanel/files/3883027/gr.zip)

**Comment by istiak101** [comment]
solved https://github.com/usmannasir/cyberpanel/commit/73bb9da0b9292e3619d0086d4e0774bae763e0bc

**Pull request closed without merging**
