### PR TITLE
Revamped Italian translation

### PR DESCRIPTION
**Pull request by maicol07**
*   Added missing translations
*   Improved existing ones

**Current status**: 100% (finished and ready to merge/review)

### CODE REVIEW

**Comment by jordanlambrecht** [comment]
@maicol07 Any updates on this? Are you still working on it?

**Comment by maicol07** [comment]
@jordanlambrecht yes, I'm working on it with an offline editor. I'm at 25% approximately.

**Comment by jordanlambrecht** [comment]
@maicol07 Awesome! Thank you! It would be dope to have this ready to go for the new version that's rolling out soon.

**Comment by maicol07** [comment]
@jordanlambrecht PR ready!

Two questions: is the stable branch the right one to merge this PR with? Have other strings been pushed to the repo in the meantime this PR was a draft?

**Pull request merged**
