### PR TITLE
Update php versions - V2.3.5

### PR DESCRIPTION
**Pull request by master3395**
This change adds php 80, 81, and 82 to the missing places. And removes the .bak file from the read me.
Updating the readme to add php 8.2
Add php limit extension for php 7 and 8

### CODE REVIEW

**Comment by usmannasir** [comment]
I don't see any of these files used anywhere?

**Comment by master3395** [comment]
The files in install/phpconfigs/php82.conf
Are used in the vhost config setup, when you use the dropdown, from what I can see.
It might also have something to do with remotebackup?
The readme file is the main file on the front of GitHub.
Also there was an extra .bak file there also.
Not sure if /install/php-configs/www.conf is used for anything.

**Comment by master3395** [comment]
bilde

**Comment by fredroo** [comment]
@master3395 thanks version 8.2 is great

**Comment by fredroo** [comment]
> I don't see any of these files used anywhere?

explain to @master3395 how to fix, PHP 8.2 is great

**Pull request closed without merging**
