### PR TITLE
V2.3.5 dev

### PR DESCRIPTION
**Pull request by master3395**
Trying to add an internal Upgrade of CyberPanel, so the users don't have to use SSH every time.

### CODE REVIEW

**Comment by usmannasir** [comment]
Let me check this, many thanks.

**Comment by usmannasir** [comment]
@master3395  did you check installation? Even installation is not going through after the merge.

**Comment by master3395** [comment]
The installation worked fine for me, but i had a problem with the views.py, where the theme wasn't as it should be.
It wasn't loading the theme, but the sub menus were working fine.
It was only the main home page that wasn't working, and the /base/versionManagment that wasn't loading correctly.

**Comment by usmannasir** [comment]
can you try installing v2.3.5-dev?

**Comment by master3395** [comment]
I will fire up a Virtualbox, to try, since my current VPS is in use.

**Comment by usmannasir** [comment]
you can contact our team if you need a vm to test.

**Comment by master3395** [comment]
I guess we should revert until future notice.
So we know everything works first.

**Comment by usmannasir** [comment]
Its the dev branch only.

**Comment by master3395** [comment]
I am getting closer at least.
Sadly when clicking the button, it doesn't start the upgrade yet.
image

**Comment by master3395** [comment]
The main issue is that CyberPanel does not execute the upgrade for some reason.
I even added a way to choose what branch to upgrade to.

image

**Pull request merged**
