### PR TITLE
assign post_max_size to fix https://github.com/usmannasir/cyberpanel/issues/1163

### PR DESCRIPTION
**Pull request by Lvl4Sword**
I think this is all that's needed here, as the error is pretty straightforward.

### CODE REVIEW

**Comment by Lvl4Sword** [comment]
Should [Django's JsonResponse](https://docs.djangoproject.com/en/dev/ref/request-response/#jsonresponse-objects) be used in `fetchPHPExtensions` rather than the `HttpResponse` used here?

**Comment by Lvl4Sword** [comment]
listChildDomainsJson was added and will fix https://github.com/usmannasir/cyberpanel/issues/1120
Also did args.function.lower() so cli commands don't need specific casing.

**Comment by Lvl4Sword** [comment]
Weirdly enough listChildDomainsJson brings back `PHP 7.3` for php_version. Are child domains setting PHP incorrectly?

**Comment by Lvl4Sword** [comment]
@usmannasir Can you take a look at this?

**Comment by usmannasir** [comment]
I am sorry I was out of the country. Right now I can see that only the cli file is changed?

**Pull request closed without merging**
