### PR TITLE
Add support for openEuler and bug fixes

### PR DESCRIPTION
**Pull request by aaronsmile**
1.Added install support for openEuler 20.03LTS and 22.03LTS with YARO(Yet Another Repository for openEuler).
2.Fixed the bug when install restic on CentOS 8, now it can be installed directly through EPEL.
3.Updated some text descriptions.

### CODE REVIEW

**Review by aaronsmile — COMMENTED** [review]
use redhat-release instead of os-release to judge the OS more accurately
for openEuler, use openEuler-release

**Comment by usmannasir** [comment]
I will have to do lots of internal work to make it fully work, openEuler is something really good and important? tbh I heard the first time

**Comment by aaronsmile** [comment]
Hello, openEuler is a young operating system. Some of its features come from the EulerOS that Huawei has put into commercial use for nearly 10 years.
Although there are not many users at present, I believe that with the iteration of the version and the contribution of the community, it will occupy a place in the field of server operating systems.
In fact, I am the administrator of YARO. With the help of qtwrk, I compiled lsphp and other packages suitable for CyberPanel to make openEuler easier to use. I will try my best to maintain it.
Thank you for your dedication to CyberPanel!

**Comment by usmannasir** [comment]
Thanks, and do you know any provider where I can install openEuler?

**Comment by aaronsmile** [comment]
It supports installation on VPS or physical server of any service provider! For me, if VNC is available, the most convenient way is through netboot.xyz for network installation. If you need help, please feel free to contact me

**Comment by aaronsmile** [comment]
This page may help you boot netboot.xyz.iso using GRUB on Ubuntu or Debian:
https://netboot.xyz/docs/booting/grub

**Comment by usmannasir** [comment]
ok, which means have to do manually.

I will look into this, thanks again.

**Pull request merged**
