### PR TITLE
Change default password to random

### PR DESCRIPTION
**Pull request by nickchomey**
There is no reason at all that the default should be 1234567. In fact, that shouldn't even be an option. This sets the default to a random 16 character pw, or you can manually set one that is 8 characters or more.

### CODE REVIEW

**Comment by nickchomey** [comment]
This still needs some work - I see a bunch of other places where the password mechanism is implemented and will need to be changed.

**Comment by nickchomey** [comment]
I think it is ready now. Please review.

**Comment by master3395** [comment]
How about we then use the "random" password you get to CP as OLS password at the same time?

(Command below might be wrong but you get the idea)
Atm the user can still change the password manually for OLS inside OLS.

`echo "echo \$@ > /etc/cyberpanel/adminPass" >> /usr/bin/adminPass`

**Comment by usmannasir** [comment]
Nick I will have to close this because users get an option to either deploy default or random password, it will confuse them.

**Comment by jordantrizz** [comment]
> Nick I will have to close this because users get an option to either deploy default or random password, it will confuse them.

Can you elaborate? you shouldn't be giving them an option, just a randomized password.

**Comment by nickchomey** [comment]
And, moreover, if this PR had actually been reviewed, you'd have seen that i fully removed the default option and made random the default. So its just Random/Custom. If they want to manually set it to 1234567, that's their choice. But by default Cyberpanel should be protecting its users

**Pull request closed without merging**
