### PR TITLE
Fix/master slave dns

### PR DESCRIPTION
**Pull request by bigmatrixcouk**
The script now selects the right pdns.conf path according to OS;
Removed unnecessary addition of /32 (subnets) if IP is not set. Previously line allow-axfr-ips had "/32, /32, /32" and PDNS was unable to start, because of empty IP's in the line;
In master configuration, now it actually moves the temp file to its correct location (previously temp file was moved only in slave configuration, therefore for a lot of people master/slave configuration never worked).
These changes were tested and are working in ubuntu.

### CODE REVIEW

**Comment by usmannasir** [comment]
Did you check on centos 7 and 8 ?

**Comment by bigmatrixcouk** [comment]
Just finished testing on centos 7. Alll working
Now will test on centos 8.

Progress:
Ubuntu 20.04 - TESTED - WORKING
CentOS 7 - TESTED - WORKING

**Comment by usmannasir** [comment]
thanks, keep me posted.

**Comment by bigmatrixcouk** [comment]
Progress:
Ubuntu 20.04 - TESTED - WORKING
CentOS 7 - TESTED - WORKING
CentOS8 - TESTED - WORKING

Just a side note, on centos 8 SELinux is preventing pdns process from:
Reding pdns.conf;
Opening UDP 16518 for bind.

Both errors:
Mar 16 18:11:37 localhost.localdomain setroubleshoot[9092]: SELinux is preventing /usr/sbin/pdns_server from read access on the file pdns.conf. For complete SELinux messages run: sealert -l 8231de34-d856-4b80-80c8-6af9d7754c2f
Mar 16 18:11:37 localhost.localdomain setroubleshoot[9092]: SELinux is preventing /usr/sbin/pdns_server from read access on the file pdns.conf.
                                                            If you believe that pdns_server should be allowed read access on the pdns.conf file by default.
                                                            # ausearch -c 'pdns_server' --raw | audit2allow -M my-pdnsserver
                                                            # semodule -X 300 -i my-pdnsserver.pp
Mar 16 18:11:51 localhost.localdomain setroubleshoot[9119]: SELinux is preventing pdns/comm-main from name_bind access on the udp_socket port 16518. For complete SELinux messages run: sealert -l 6de9c0bb-cc8b-49da-98a5-b29742a87d48
Mar 16 18:11:51 localhost.localdomain setroubleshoot[9119]: SELinux is preventing pdns/comm-main from name_bind access on the udp_socket port 16518.
                                                            If you want to allow pdns/comm-main to bind to network port 16518
                                                            # ausearch -c 'pdns/comm-main' --raw | audit2allow -M my-pdnscommmain
                                                            # semodule -X 300 -i my-pdnscommmain.pp

We can investigate this in new PR, because it's not related?

**Comment by usmannasir** [comment]
selinux should be disabled prior to CP installation. I will merge this now.

**Pull request merged**
